#!/usr/bin/env sh


## create a new file for writing - visudo uses the vim editor by default.
## go read about this if you have no idea what is going on.
#
#sudo visudo -f /private/etc/sudoers.d/yabai
#
## input the line below into the file you are editing.
##  replace <yabai> with the path to the yabai binary (output of: which yabai).
##  replace <user> with your username (output of: whoami). 
##  replace <hash> with the sha256 hash of the yabai binary (output of: shasum -a 256 $(which yabai)).
##   this hash must be updated manually after upgrading yabai.
#
#<user> ALL=(root) NOPASSWD: sha256:<hash> <yabai> --load-sa

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# .. more yabai startup stuff
#

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off	        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.80           \
    window_opacity               on            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
	# --space 2 layout			 float			\
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

echo "yabai configuration loaded.." ----------------------------
